<?php
/*********************************************************************************
 *
 * Copyright (C) 2008 Rodrigo Saiz Camarero (http://www.regoluna.com)
 *
 * This file is part of "Regoluna® Spanish Invoices" module.
 *
 * "Regoluna® Spanish Invoices" is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, version 3 of the License.
 *
 ********************************************************************************/
$dictionary['reg_items'] = array(
	'table'=>'reg_items',
	'audited'=>true,
	'fields'=>array (
  'type' =>
  array (
    'required' => false,
    'name' => 'type',
    'vname' => 'LBL_TIPO',
    'type' => 'enum',
    'massupdate' => '1',
    'default' => 'product',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 0,
    'len' => 100,
    'options' => 'producto_type_list',
    'studio' => 'visible',
  ),
  'unit_price' =>
  array (
    'required' => false,
    'name' => 'unit_price',
    'vname' => 'LBL_PRECIO_UD',
    'type' => 'float',
    'dbtype' => 'decimal',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 0,
    'len' => 26,
    'precision'=> 2,
  ),
  'unit' =>
  array (
    'required' => false,
    'name' => 'unit',
    'type' => 'enum',
    'options' => 'item_unit_dom',
    'vname' => 'LBL_UNIDAD',
    //'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 0,
    'len' => '25',
  ),
  'custom_unit' =>
  array (
    'required' => false,
    'name' => 'custom_unit',
    'type' => 'varchar',
    'vname' => 'LBL_UNIDAD_CUSTOM',
    //'type' => 'varchar',
    'massupdate' => 1,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 0,
    'len' => '15',
  ),
  'qty' =>
  array (
    'required' => '1',
    'name' => 'qty',
    'vname' => 'LBL_CANTIDAD',
    'type' => 'float',
    'dbtype' => 'decimal',
    'massupdate' => 0,
    'default' => 1,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'audited' => 1,
    'reportable' => 0,
    'len' => '26',
    'precision'=> 2,
    //'disable_num_format' => '1',
  ),
  'ordered' =>
  array (
    'required' => true,
    'name' => 'ordered',
    'vname' => 'LBL_ORDEN',
    'type' => 'int',
    'massupdate' => 0,
    'default' => NULL,
    'duplicate_merge' => 'disabled',
    'audited' => 0,
    'reportable' => 0,
    //'len' => '11',
    //'disable_num_format' => '',
  ),
  'tax_type' =>
  array (
    'required' => false,
    'name' => 'tax_type',
    'vname' => 'LBL_TIPO_IMPUESTO',
    'type' => 'enum',
    'options' => 'reg_tax_type_dom',
    //'dbtype' => 'float',
    'massupdate' => 0,
    'default' => '',
    'comments' => '',
    'help' => 'Que tipo de impuesto repercutido se aplicara al item',
    'importable' => 'true',
    'audited' => 0,
    'reportable' => 0,
    'len' => '18',
    'precision' => '0',
    'disable_num_format' => '1'
  ),
  'retention' =>
  array (
    'required' => false,
    'name' => 'retention',
    'vname' => 'LBL_RETENCION',
    'type' => 'float',
    'dbtype' => 'float',
    'massupdate' => 0,
    'default' => null,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 0,
    //'len' => '18',
    'precision' => '0',
    'disable_num_format' => '1'
  ),
  'tax' =>
  array (
    'required' => false,
    'name' => 'tax',
    'vname' => 'LBL_REPERCUTIDO',
    'type' => 'float',
    'massupdate' => 0,
    'default' => null,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 1,
    'reportable' => 0,
    //'len' => '18',
    'precision' => '0',
  ),
  'discount' =>
  array (
    'required' => false,
    'name' => 'discount',
    'vname' => 'LBL_DESCUENTO',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 1,
    'reportable' => 0,
    'len' => '25',
    'disable_num_format' => '1'
  ),
  'total_base' =>
  array (
    'required' => false,
    'name' => 'total_base',
    'vname' => 'LBL_TOTAL_ANTES',
    'type' => 'float',
    'massupdate' => 0,
    'default' => NULL,
    'comments' => 'Cantidad total antes de aplicar impuestos',
    'help' => '',
    'importable' => false,
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 0,
    'len' => '18',
    'precision' => '2',
  ),
  'total_discount' =>
  array (
    'required' => false,
    'name' => 'total_discount',
    'vname' => 'LBL_TOTAL_DESCUENTO',
    'type' => 'float',
    'massupdate' => 0,
    'default' => NULL,
    'comments' => 'Cantidad total antes de aplicar impuestos',
    'help' => '',
    'importable' => false,
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 0,
    'len' => '18',
    'precision' => '2',
  ),
//  'total' =>
//  array (
//    'required' => false,
//    'name' => 'total_base',
//    'vname' => '0',
//    'type' => 'float',
//    'massupdate' => 0,
//    'default' => NULL,
//    'comments' => 'Cantidad total final',
//    'help' => '',
//    'importable' => false,
//    'duplicate_merge' => 'disabled',
//    'duplicate_merge_dom_value' => '0',
//    'audited' => 0,
//    'reportable' => 0,
//    'len' => '18',
//    'precision' => '2',
//  ),
  'total_tax' =>
  array (
    'required' => false,
    'name' => 'total_tax',
    'vname' => 'LBL_TOTAL_IMPUESTO',
    'type' => 'float',
    'massupdate' => 0,
    'default' => NULL,
    'comments' => 'Importe de impuestos',
    'help' => '',
    'importable' => false,
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 0,
    'len' => '18',
    'precision' => '2',
  ),
  'total_retention' =>
  array (
    'required' => false,
    'name' => 'total_retention',
    'vname' => 'LBL_TOTAL_RETENCION',
    'type' => 'float',
    'massupdate' => 0,
    'default' => NULL,
    'comments' => 'Importe de impuestos',
    'help' => '',
    'importable' => false,
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 0,
    'len' => '18',
    'precision' => '2',
  ),

  // Related Invoice
	'invoice_id' => array (
	  'name' => 'invoice_id',
	  'required' => 'true',
	  'type' => 'id',
	  'audited' => 0,
	  'reportable' => 0,
	  'vname' => 'LBL_FACTURA',
	),
  'invoice_name' => array (
    'name' => 'invoice_name',
    'type' => 'relate',
    'source' => 'non-db',
    'vname' => 'LBL_FACTURA',
    'id_name' => 'invoice_id',
    'table' => 'reg_invoices',
    'module' => 'reg_invoices',
    'ext2' => 'reg_invoices',
  ),
	    

),
	'relationships'=>array (
),
	'optimistic_lock'=>true,
);
require_once('include/SugarObjects/VardefManager.php');
VardefManager::createVardef('reg_items','reg_items', array('basic','assignable'));