<?php
/*********************************************************************************
 * 
 * Copyright (C) 2008 Rodrigo Saiz Camarero (http://www.regoluna.com)
 *
 * This file is part of "Regoluna® Spanish Invoices" module.
 *
 * "Regoluna® Spanish Invoices" is free software: you can redistribute it and/or 
 * modify it under the terms of the GNU Lesser General Public License as published 
 * by the Free Software Foundation, version 3 of the License.
 *   
 ********************************************************************************/
$dictionary['fact_Items'] = array(
	'table'=>'fact_items',
	'audited'=>true,
	'fields'=>array (
  'tipo' => 
  array (
    'required' => false,
    'name' => 'tipo',
    'vname' => 'LBL_TIPO',
    'type' => 'enum',
    'massupdate' => '1',
    'default' => 'product',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 0,
    'len' => 100,
    'options' => 'producto_tipo_list',
    'studio' => 'visible',
  ),
  'precio_ud' => 
  array (
    'required' => false,
    'name' => 'precio_ud',
    'vname' => 'LBL_PRECIO_UD',
    'type' => 'float',
    'dbtype' => 'decimal',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 0,
    'len' => 26,
    'precision'=> 2,
  ),
  'unidad' => 
  array (
    'required' => false,
    'name' => 'unidad',
    'type' => 'enum',
    'options' => 'item_unit_dom',
    'vname' => 'LBL_UNIDAD',
    //'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 0,
    'len' => '25',
  ),
  'unidad_custom' => 
  array (
    'required' => false,
    'name' => 'unidad_custom',
    'type' => 'varchar',
    'vname' => 'LBL_UNIDAD_CUSTOM',
    //'type' => 'varchar',
    'massupdate' => 1,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 0,
    'len' => '15',
  ),
  'cantidad' => 
  array (
    'required' => '1',
    'name' => 'cantidad',
    'vname' => 'LBL_CANTIDAD',
    'type' => 'float',
    'dbtype' => 'decimal',
    'massupdate' => 0,
    'default' => 1,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'audited' => 1,
    'reportable' => 0,
    'len' => '26',
    'precision'=> 2,
    //'disable_num_format' => '1',
  ),
  'orden' => 
  array (
    'required' => '1',
    'name' => 'orden',
    'vname' => 'LBL_ORDEN',
    'type' => 'int',
    'massupdate' => 0,
    'default' => NULL,
    'duplicate_merge' => 'disabled',
    'audited' => 0,
    'reportable' => 0,
    'len' => '11',
    //'disable_num_format' => '',
  ),
  'tipo_repercutido' => 
  array (
    'required' => false,
    'name' => 'tipo_repercutido',
    'vname' => 'LBL_TIPO_IMPUESTO',
    'type' => 'enum',
    'options' => 'tipo_impuesto_dom',
    //'dbtype' => 'float',
    'massupdate' => 0,
    'default' => '',
    'comments' => '',
    'help' => 'Que tipo de impuesto repercutido se aplicara al item',
    'importable' => 'true',
    'audited' => 0,
    'reportable' => 0,
    'len' => '18',
    'precision' => '0',
    'disable_num_format' => '1'
  ),
  'retencion' => 
  array (
    'required' => false,
    'name' => 'retencion',
    'vname' => 'LBL_RETENCION',
    'type' => 'float',
    'dbtype' => 'float',
    'massupdate' => 0,
    'default' => null,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 0,
    //'len' => '18',
    'precision' => '0',
    'disable_num_format' => '1'
  ),
  'impuesto' => 
  array (
    'required' => false,
    'name' => 'impuesto',
    'vname' => 'LBL_REPERCUTIDO',
    'type' => 'float',
    'massupdate' => 0,
    'default' => null,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 1,
    'reportable' => 0,
    //'len' => '18',
    'precision' => '0',
  ),
  'descuento' => 
  array (
    'required' => false,
    'name' => 'descuento',
    'vname' => 'LBL_DESCUENTO',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 1,
    'reportable' => 0,
    'len' => '25',
    'disable_num_format' => '1'
  ),
  'total_antes' => 
  array (
    'required' => false,
    'name' => 'total_antes',
    'vname' => 'LBL_TOTAL_ANTES',
    'type' => 'float',
    'massupdate' => 0,
    'default' => NULL,
    'comments' => 'Cantidad total antes de aplicar impuestos',
    'help' => '',
    'importable' => false,
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 0,
    'len' => '18',
    'precision' => '2',
  ),
  'total_descuento' => 
  array (
    'required' => false,
    'name' => 'total_descuento',
    'vname' => 'LBL_TOTAL_DESCUENTO',
    'type' => 'float',
    'massupdate' => 0,
    'default' => NULL,
    'comments' => 'Cantidad total antes de aplicar impuestos',
    'help' => '',
    'importable' => false,
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 0,
    'len' => '18',
    'precision' => '2',
  ),
//  'total' => 
//  array (
//    'required' => false,
//    'name' => 'total_antes',
//    'vname' => '0',
//    'type' => 'float',
//    'massupdate' => 0,
//    'default' => NULL,
//    'comments' => 'Cantidad total final',
//    'help' => '',
//    'importable' => false,
//    'duplicate_merge' => 'disabled',
//    'duplicate_merge_dom_value' => '0',
//    'audited' => 0,
//    'reportable' => 0,
//    'len' => '18',
//    'precision' => '2',
//  ),
  'total_impuesto' => 
  array (
    'required' => false,
    'name' => 'total_impuesto',
    'vname' => 'LBL_TOTAL_IMPUESTO',
    'type' => 'float',
    'massupdate' => 0,
    'default' => NULL,
    'comments' => 'Importe de impuestos',
    'help' => '',
    'importable' => false,
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 0,
    'len' => '18',
    'precision' => '2',
  ),
  'total_retencion' => 
  array (
    'required' => false,
    'name' => 'total_retencion',
    'vname' => 'LBL_TOTAL_RETENCION',
    'type' => 'float',
    'massupdate' => 0,
    'default' => NULL,
    'comments' => 'Importe de impuestos',
    'help' => '',
    'importable' => false,
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 0,
    'len' => '18',
    'precision' => '2',
  ),
  
  // Relación con Factura
  "factura" => array (
    'name' => 'factura',
    'type' => 'link',
    'relationship' => 'factura_items',
    'source' => 'non-db',
    'side' => 'right',
    'vname' => 'LBL_FACTURA',
  ),
  "factura_name" => array (
    'name' => 'factura_name',
    'type' => 'relate',
    'source' => 'non-db',
    'vname' => 'LBL_FACTURA',
    'save' => true,
    'id_name' => 'factura_id',
    'link' => 'factura',
    'table' => 'fact_facturas',
    'module' => 'fact_Facturas',
    'rname' => 'name',
  ), 
  "factura_id" => array (
    'name' => 'factura_id',
    'type' => 'link',
    'relationship' => 'factura_items',
    'source' => 'non-db',
    'side' => 'right',
    'vname' => 'LBL_FACTURA',
  ),
  
),
	'relationships'=>array (
),
	'optimistic_lock'=>true,
);
require_once('include/SugarObjects/VardefManager.php');
VardefManager::createVardef('fact_Items','fact_Items', array('basic','assignable'));